### ISSUE TITLE
VS/CS CH AllergyIntolerance (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-term#33]
Change status & experimental after review
* status: draft -> acitve
* experimental: true -> false

see https://github.com/hl7ch/ch-allergyintolerance/issues/91#issuecomment-1971045959

please also have a look into the qa of CH AllergyIntolerance, there are some infos/warnings concerning the terminology

**Comment by pjolo** [comment]
Typo in Allergy term corrected:
[Commit](https://github.com/hl7ch/ch-epr-term/commit/226c5c72fa36ac853a7eb5b4bba663831f159852)
