### ISSUE TITLE
CH VACD Swiss Recommendation Forecast Status (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-term#52]
ch.fhir.ig.ch-term#3.0.0 /ValueSet-ch-vacd-recommendation-forecast-status-vs.html

Additional Language Displays: Missing translations dt. fr. it. rm

Marcel Hanselmann

**Comment by ralych** [comment]
@pjolo please let check the translations done with deepl.

**Comment by pjolo** [comment]
@ralych I have requested the translation internally and it should be ready next week. As soon as I receive the translations, I will insert them here.

**Comment by ralych** [comment]
https://build.fhir.org/ig/hl7ch/ch-term/branches/52-ch-vacd-swiss-recommendation-forecast-status-marcel-hanselmann/index.html
