### ISSUE TITLE
CH VACD Swissmedic Authorized Vaccines (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-term#53]
ch.fhir.ig.ch-term#3.0.0 /CodeSystem-ch-vacd-swissmedic-cs.html

Is there a possibility to exchange data of non-label vaccines, like actually Monkeypox [Mpox]?
[ https://www.bag.admin.ch/bag/de/home/krankheiten/krankheiten-im-ueberblick/mpox.html ]

Marcel Hanselmann

**Comment by ralych** [comment]
see also https://github.com/hl7ch/ch-vacd/issues/269

**Comment by ralych** [comment]
In meantime [Mpox](https://build.fhir.org/ig/hl7ch/ch-term/CodeSystem-ch-vacd-swissmedic-cs.html#ch-vacd-swissmedic-cs-69403) is not anymore an off label vaccine in CH.

in the ch-vacd [Immunization resource profile](https://fhir.ch/ig/ch-vacd/StructureDefinition-ch-vacd-immunization-definitions.html#diff_Immunization.vaccineCode) the valueset is as extensible declared.
The vaccineCode can also be defined using [snomed-ct codes](https://build.fhir.org/ig/hl7ch/ch-term/ValueSet-ch-vacd-vaccines-snomedct-vs.html).

**Comment by lpg-tech** [comment]
Explanation is clear.
