### ISSUE TITLE
experimental (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-term#54]
When working with VS which are experimental (e.g. ValueSet: CH AllergyIntolerance (Experimental)), the publisher shows the following warning:

warning: The definition for the element 'AllergyIntolerance.code' binds to the value set 'http://fhir.ch/ig/ch-allergyintolerance/ValueSet/CHAllergyIntoleranceValueSet' which is experimental, but this structure is not labeled as experimental

should we really have the status experimental?

see also https://github.com/hl7ch/ch-term/issues/33

may check all artifacts concerning this topic

**Comment by pjolo** [comment]
@ziegm 
We should change the status from draft to active and experimental from true to false as mentioned in Issue #33.

**Comment by ziegm** [comment]
There is some inconsistency (or I mix up something):

https://fhir.ch/ig/ch-term/ValueSet-CHAllergyIntoleranceValueSet.json.html
meta.source = "http://art-decor.org/fhir/ValueSet/2.16.756.5.30.1.1.11.82--20200925110235"

but in Art Decor the OID 2.16.756.5.30.1.1.11.82 is for ActivePharmaceuticalIngredient
https://art-decor.org/art-decor/decor-valuesets--ch-pharm-?id=2.16.756.5.30.1.1.11.82&effectiveDate=2020-09-25T11:02:35

@pjolo @oliveregger can you see the reason for that? what is the source of this value set?

**Comment by ziegm** [comment]
Check artifacts in CH Term for draft and experimental:

| Type | Artifact | Actual | Target |
|------|----------------------------------------------------------------------------------------------------|---------------------------------------------|--------|
| CS | http://fhir.ch/ig/ch-allergyintolerance/CodeSystem/allergyintolerance-clinical-supplement | status = draft, experimental = true | |
| CS | http://fhir.ch/ig/ch-allergyintolerance/CodeSystem/allergyintolerance-verification-supplement | status = draft, experimental = true | |
| CS | http://fhir.ch/ig/ch-allergyintolerance/CodeSystem/allergyintolerance-type-supplement | status = draft, experimental = true | |
| CS | http://fhir.ch/ig/ch-allergyintolerance/CodeSystem/allergyintolerance-criticality-supplement | status = draft, experimental = true | |
| CS | http://fhir.ch/ig/ch-allergyintolerance/CodeSystem/allergyintolerance-severity-supplement | status = draft, experimental = true | |
| CS | http://fhir.ch/ig/ch-allergyintolerance/CodeSystem/allergyintolerance-category-supplement | status = draft, experimental = true | |
| Map | Snomed CT VaccineCode To SwissMedic VaccineCode | status = draft, experimental = false | |
| Map | Mappings from vaccine code to vaccine code | status = draft, experimental = false | |
| VS | http://fhir.ch/ig/ch-allergyintolerance/ValueSet/CHAllergyIntoleranceReactionManifestationValueSet | status = draft, experimental = true | |
| VS | http://fhir.ch/ig/ch-allergyintolerance/ValueSet/CHAllergyIntoleranceReactionSubstanceValueSet | status = draft, experimental = true | |
| VS | http://fhir.ch/ig/ch-allergyintolerance/ValueSet/CHAllergyIntoleranceValueSet | status = draft, experimental = true | |
| VS | http://fhir.ch/ig/ch-allergyintolerance/ValueSet/CHAllergyIntoleranceConditionValueSet | status = draft, experimental = true | |

**Comment by oliveregger** [comment]
@ziegm we did not directly export them from art-decor are they managed directly in the IG?

**Comment by ralych** [comment]
ch-vacd is not from art decor. all directly in the IGi do not understand what de issue is about?Am 03.10.2024 um 14:14 schrieb Oliver Egger ***@***.***>:﻿
@ziegm we did not directly export them from art-decor are they managed directly in the IG?
